### ISSUE TITLE
Issue when using this library 

### ISSUE THREAD

**Issue by rcusters** [tmorin/plantuml-libs#1]
Hi,

When I try to use the event storming library to create a diagram I get the error in attachment.
Is this a know issue?

Kind regards
Robin
![test_event_storming](https://user-images.githubusercontent.com/3646299/81398148-f4ccc000-9128-11ea-844f-a54bbacb1797.png)

**Comment by tmorin** [comment]
Hi,

The issue should be fixed.
Thanks for the report.

Best regards
